TERMINOLOGY = {
    "en": {"risk_high": "HIGH risk", "risk_extreme": "EXTREME risk", "unavailable": "Marine data is unavailable.", "pfz": "Potential Fishing Zone (PFZ)", "route": "Suggested route", "lower_risk_route": "Suggested lower-risk route", "direct_distance": "Direct distance", "detour": "Detour", "destination_restricted": "Destination restricted", "no_feasible_route": "No feasible route", "route_warning": "Route warning", "restricted_waters": "Restricted waters", "maritime_boundary": "International maritime boundary", "protected_area": "Protected area", "caution_zone": "Caution zone", "prohibited_zone": "Prohibited zone", "weather": "Weather", "marine": "Marine conditions", "alerts": "Alerts", "source": "Source"},
    "hi": {"risk_high": "उच्च जोखिम (HIGH)", "risk_extreme": "अत्यधिक जोखिम (EXTREME)", "unavailable": "समुद्री डेटा उपलब्ध नहीं है।", "pfz": "संभावित मछली पकड़ने का क्षेत्र (PFZ)", "weather": "मौसम", "marine": "समुद्री परिस्थितियाँ", "alerts": "चेतावनियाँ", "source": "स्रोत"},
    "hi-Latn": {"risk_high": "HIGH risk", "risk_extreme": "EXTREME risk", "unavailable": "Marine data available nahi hai.", "pfz": "Potential Fishing Zone (PFZ)", "weather": "Mausam", "marine": "Marine conditions", "alerts": "Alerts", "source": "Source"},
    "ta": {"risk_high": "உயர் அபாயம் (HIGH)", "risk_extreme": "மிக அதிக அபாயம் (EXTREME)", "unavailable": "கடல் தரவு கிடைக்கவில்லை.", "pfz": "சாத்தியமான மீன்பிடி மண்டலம் (PFZ)", "weather": "வானிலை", "marine": "கடல் நிலை", "alerts": "எச்சரிக்கைகள்", "source": "மூலம்"},
    "te": {"risk_high": "అధిక ప్రమాదం (HIGH)", "risk_extreme": "తీవ్ర ప్రమాదం (EXTREME)", "unavailable": "సముద్ర డేటా అందుబాటులో లేదు.", "pfz": "చేపల వేట జోన్ (PFZ)", "weather": "వాతావరణం", "marine": "సముద్ర పరిస్థితులు", "alerts": "హెచ్చరికలు", "source": "మూలం"},
    "ml": {"risk_high": "ഉയർന്ന അപകടസാധ്യത (HIGH)", "risk_extreme": "അതീവ അപകടസാധ്യത (EXTREME)", "unavailable": "സമുദ്ര വിവരങ്ങൾ ലഭ്യമല്ല.", "pfz": "മത്സ്യബന്ധന മേഖല (PFZ)", "weather": "കാലാവസ്ഥ", "marine": "സമുദ്രാവസ്ഥ", "alerts": "മുന്നറിയിപ്പുകൾ", "source": "ഉറവിടം"},
    "gu": {"risk_high": "ઉચ્ચ જોખમ (HIGH)", "risk_extreme": "અતિ જોખમ (EXTREME)", "unavailable": "દરિયાઈ માહિતી ઉપલબ્ધ નથી.", "pfz": "સંભવિત માછીમારી ઝોન (PFZ)", "weather": "હવામાન", "marine": "દરિયાઈ સ્થિતિ", "alerts": "ચેતવણીઓ", "source": "સ્ત્રોત"},
    "mr": {"risk_high": "उच्च धोका (HIGH)", "risk_extreme": "अत्यंत धोका (EXTREME)", "unavailable": "सागरी डेटा उपलब्ध नाही.", "pfz": "संभाव्य मासेमारी क्षेत्र (PFZ)", "weather": "हवामान", "marine": "सागरी स्थिती", "alerts": "इशारे", "source": "स्रोत"},
    "bn": {"risk_high": "উচ্চ ঝুঁকি (HIGH)", "risk_extreme": "চরম ঝুঁকি (EXTREME)", "unavailable": "সামুদ্রিক তথ্য উপলব্ধ নয়।", "pfz": "সম্ভাব্য মৎস্য অঞ্চল (PFZ)", "weather": "আবহাওয়া", "marine": "সামুদ্রিক অবস্থা", "alerts": "সতর্কতা", "source": "উৎস"},
    "or": {"risk_high": "ଉଚ୍ଚ ବିପଦ (HIGH)", "risk_extreme": "ଅତ୍ୟଧିକ ବିପଦ (EXTREME)", "unavailable": "ସାମୁଦ୍ରିକ ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ।", "pfz": "ମତ୍ସ୍ୟ କ୍ଷେତ୍ର (PFZ)", "weather": "ପାଣିପାଗ", "marine": "ସାମୁଦ୍ରିକ ସ୍ଥିତି", "alerts": "ଚେତାବନୀ", "source": "ଉତ୍ସ"},
    "kn": {"risk_high": "ಹೆಚ್ಚಿನ ಅಪಾಯ (HIGH)", "risk_extreme": "ತೀವ್ರ ಅಪಾಯ (EXTREME)", "unavailable": "ಸಮುದ್ರ ದತ್ತಾಂಶ ಲಭ್ಯವಿಲ್ಲ.", "pfz": "ಮೀನುಗಾರಿಕಾ ವಲಯ (PFZ)", "weather": "ಹವಾಮಾನ", "marine": "ಸಮುದ್ರ ಪರಿಸ್ಥಿತಿ", "alerts": "ಎಚ್ಚರಿಕೆಗಳು", "source": "ಮೂಲ"},
}

