"use client";
import {FormEvent,useState} from "react";
import {Bot,LoaderCircle,MapPin,Send} from "lucide-react";
import {MarineMap} from "@/components/marine-map";
import {DemoDataBadge,PageHeader} from "@/components/ui";
import {extractQuery,planQuery} from "@/lib/api/ai";
import type {ExecutionPlan,QueryExtraction} from "@/features/ai/types";

export default function AssistantPage(){
  const[query,setQuery]=useState("");const[result,setResult]=useState<QueryExtraction|null>(null);const[plan,setPlan]=useState<ExecutionPlan|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!query.trim())return;setLoading(true);setError("");try{const text=query.trim();const[extracted,planned]=await Promise.all([extractQuery(text).catch(()=>null),planQuery(text)]);setResult(extracted);setPlan(planned);}catch(cause){setResult(null);setPlan(null);setError(cause instanceof Error?cause.message:"PLANNER_UNAVAILABLE");}finally{setLoading(false);}};
  return <div className="page assistant-page"><PageHeader eyebrow="LANGUAGE INTELLIGENCE" title="ORCA Query Planner" subtitle="Structured extraction and deterministic planning only. No marine tools are executed in Step 12." action={<DemoDataBadge label="Step 12 Development"/>}/><div className="assistant-layout"><section className="chat-panel"><div className="chat-welcome"><span><Bot size={20}/></span><h2>Inspect a marine query</h2><p>Try English, Hindi, or Hinglish. ORCA preserves the original query and does not geocode place names.</p></div><form className="assistant-input" onSubmit={submit}><input aria-label="Marine query" maxLength={4000} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Is it safe tomorrow morning near Chennai?"/><button disabled={loading} aria-label="Plan query">{loading?<LoaderCircle className="spin" size={17}/>:<Send size={17}/>}</button></form>{error&&<p className="auth-error" role="alert">{error}</p>}{(result||plan)&&<section className="agent-activity" aria-live="polite"><div><Bot size={17}/><strong>Validated extraction and execution plan</strong></div>{result&&<ol><li><i className="done"/>Language: {result.language.language_name}</li><li><i className="done"/>Intents: {result.possible_intents.join(", ")}</li><li><i className="done"/>Location: {result.requested_location_text??(result.latitude!=null?`${result.latitude}, ${result.longitude}`:"Not supplied")}</li><li><i className="done"/>Time: {result.requested_time_text??"Not supplied"}</li></ol>}{plan&&<><p><strong>Primary intent:</strong> {plan.primary_intent} · <strong>Tools:</strong> {plan.steps.map(step=>step.tool).join(" → ")||"None"}</p><p><strong>Dependencies:</strong> {plan.parallel_groups.map(group=>`[${group.join(", ")}]`).join(" → ")||"None"}</p><p><strong>Clarification:</strong> {plan.needs_clarification?plan.clarification_questions.join(" "):"Not needed"} · <strong>Capability:</strong> {plan.capability_status}</p></>}{process.env.NODE_ENV!=="production"&&<details className="conditions-evidence"><summary>Development debug — structured plan</summary><pre>{JSON.stringify(plan??result,null,2)}</pre></details>}</section>}</section><aside className="context-panel"><div className="context-title"><div><p className="eyebrow">PLANNER BOUNDARY</p><h3>No tools executed</h3></div><MapPin size={19}/></div><MarineMap/><div className="context-facts"><div><span>Execution</span><b>Future orchestrator</b></div><div><span>Safety</span><b>Risk engine only</b></div><div><span>Tools</span><b>Allowlisted ORCA tools</b></div></div></aside></div></div>;
}
