"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, ExternalLink, MapPin } from "lucide-react";
import { AlertSafetyNote, AlertSeverityBadge, AlertSourceBadge, AlertStatusBadge, formatIst } from "@/components/alert-components";
import { MarineMap } from "@/components/marine-map";
import { PageHeader, StateBox } from "@/components/ui";
import { useAuth } from "@/components/auth-provider";
import { useSharedSelectedLocation } from "@/features/map/location-store";
import type { MarineAlert } from "@/features/alerts/types";
import type { SelectedLocation } from "@/features/map/types";
import { getAlert } from "@/lib/api/alerts";

export default function AlertDetailPage(){const params=useParams<{alertId:string}>();const {user}=useAuth();const shared=useSharedSelectedLocation();const profile:SelectedLocation|null=user?.default_latitude!=null&&user.default_longitude!=null?{latitude:user.default_latitude,longitude:user.default_longitude,source:"default",label:"Profile Default Location"}:null;const location=shared??profile;const [alert,setAlert]=useState<MarineAlert|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
  useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{setLoading(true);void getAlert(params.alertId,location?.latitude,location?.longitude).then(item=>{if(active){setAlert(item);setError(false);}},()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});},0);return()=>{active=false;window.clearTimeout(timer);};},[location?.latitude,location?.longitude,params.alertId]);
  if(loading)return <div className="page"><StateBox kind="loading" title="Loading alert" detail="Retrieving the normalized advisory record."/></div>;
  if(error||!alert)return <div className="page"><StateBox kind="error" title="Alert unavailable" detail="The record was not found or alert persistence is unavailable."/><Link className="back-link" href="/alerts"><ArrowLeft size={14}/>Back to alerts</Link></div>;
  return <div className="page alert-detail-page"><PageHeader eyebrow="MARINE ALERT DETAIL" title={alert.title} subtitle={alert.affected_area??"Provider supplied a textual advisory without mapped affected-area geometry."} action={<div className="alert-badge-row"><AlertSeverityBadge severity={alert.severity}/><AlertStatusBadge status={alert.status}/></div>}/><AlertSafetyNote/><div className="alert-detail-grid"><section className="alert-detail-card"><AlertSourceBadge sourceType={alert.source_type} provider={alert.provider}/><dl><Fact label="Alert type" value={alert.type.replaceAll("_"," ")}/><Fact label="Official summary" value={alert.summary}/><Fact label="Description" value={alert.description}/><Fact label="Affected area" value={alert.affected_area}/><Fact label="Distance" value={alert.distance_km==null?"Not available":alert.is_inside?"Selected location is inside advisory geometry":`${alert.distance_km.toFixed(1)} km from advisory geometry`}/><Fact label="Issued" value={formatIst(alert.issued_at)}/><Fact label="Valid from" value={formatIst(alert.valid_from)}/><Fact label="Valid until" value={formatIst(alert.valid_until)}/><Fact label="Freshness" value={alert.freshness}/><Fact label="Source" value={alert.source}/></dl>{alert.source_url&&<a className="button-link" href={alert.source_url} target="_blank" rel="noreferrer">Open provider source <ExternalLink size={13}/></a>}</section><section className="alert-detail-card"><h2>Instructions</h2>{alert.instructions.length?<ol>{alert.instructions.map(item=><li key={item}>{item}</li>)}</ol>:<p>No instructions were supplied in this provider record.</p>}<h2>Evidence</h2><dl><Fact label="Bulletin" value={alert.evidence.bulletin}/><Fact label="Retrieved" value={formatIst(alert.evidence.retrieved_at)}/><Fact label="Source type" value={alert.source_type.replaceAll("_"," ")}/></dl>{alert.type==="LIGHTNING"&&<p className="alert-limitations">This record is labeled as lightning risk forecast, not real-time lightning detection.</p>}</section></div><section className="alert-map-card"><div><h2>Provider geometry</h2><p>{alert.geometry?"Only geometry supplied by the provider is rendered.":"No provider geometry was supplied; ORCA has not invented a polygon."}</p></div>{alert.geometry?<MarineMap selectedLocation={location} alerts={[alert]} showDemoFeatures={false}/>:<div className="unmapped-alert"><MapPin size={22}/>Textual affected area only</div>}</section><Link className="back-link" href="/alerts"><ArrowLeft size={14}/>Back to alerts</Link></div>;
}
function Fact({label,value}:{label:string;value:string|null|undefined}){return <div><dt>{label}</dt><dd>{value||"Not supplied"}</dd></div>}
