"use client";
import {FormEvent,useState} from "react";
import {Navigation} from "lucide-react";
import {MarineMap} from "@/components/marine-map";
import {PageHeader} from "@/components/ui";
import {EvidenceFacts} from "@/components/evidence-facts";
import {apiClient} from "@/lib/api/client";
import {API_V1_PREFIX} from "@/lib/api/config";
import "../demo-polish.css";
type RouteResult={status:string;geometry:import("geojson").LineString|null;direct_distance_km:number;distance_km:number|null;route_mode:string;departure_time:string|null;risk_summary:Record<string,unknown>;geofence_summary:Record<string,unknown>;warnings:string[];limitations:string[];evidence:unknown[]};
export default function RoutesPage(){
 const[mode,setMode]=useState("LOWEST_RISK");const[result,setResult]=useState<RouteResult|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setLoading(true);setError("");setResult(null);const data=new FormData(event.currentTarget);try{setResult(await apiClient<RouteResult>(`${API_V1_PREFIX}/routes/calculate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({start:{latitude:Number(data.get("start_lat")),longitude:Number(data.get("start_lon"))},destination:{latitude:Number(data.get("end_lat")),longitude:Number(data.get("end_lon"))},route_mode:mode}),timeoutMs:30_000}));}catch(cause){setError(cause instanceof Error?cause.message:"Route unavailable");}finally{setLoading(false);}};
 return <div className="page"><PageHeader eyebrow="ROUTE INTELLIGENCE" title="Marine Route Planner" subtitle="Suggested lower-risk route; verify official navigation and local maritime advisories before departure."/>
 <div className="route-layout"><form className="route-form" onSubmit={submit}><h2>Plan a route</h2>{[{name:"start_lat",label:"Start latitude",value:13.08,max:90},{name:"start_lon",label:"Start longitude",value:80.27,max:180},{name:"end_lat",label:"Destination latitude",value:13.2,max:90},{name:"end_lon",label:"Destination longitude",value:80.5,max:180}].map(field=><label key={field.name}>{field.label}<input name={field.name} type="number" step="any" min={-field.max} max={field.max} defaultValue={field.value} required/></label>)}<label>Route mode<select value={mode} onChange={event=>setMode(event.target.value)}>{["LOWEST_RISK","BALANCED","SHORTEST_FEASIBLE"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><button className="button" disabled={loading}><Navigation size={16}/>{loading?"Planning route…":"Calculate route"}</button><p>Without verified land and environmental masks, live routing is unavailable. Explicit demo deployments return a labelled geometry demonstration.</p></form>
 <section className="route-preview"><MarineMap showDemoFeatures={false} routeGeometry={result?.geometry}/>{error&&<p role="alert">{error}</p>}{result&&<div className="assistant-result"><h3>{result.status==="DEMO"?"DEMO DATA — geometry demonstration":result.status.replaceAll("_"," ")}</h3><div className="route-summary"><div><span>Direct distance</span><b>{result.direct_distance_km.toFixed(1)} km</b></div><div><span>Suggested distance</span><b>{result.distance_km==null?"Unavailable":`${result.distance_km.toFixed(1)} km`}</b></div><div><span>Departure</span><b>{result.departure_time??"Not supplied"}</b></div><div><span>Mode</span><b>{result.route_mode.replaceAll("_"," ")}</b></div></div><h4>Marine risk and highest-risk segment</h4><p>{Object.keys(result.risk_summary).length?"See assessment below":"Unavailable — environmental masks not connected"}</p><EvidenceFacts value={result.risk_summary}/><h4>Maritime restrictions</h4><p>{Object.keys(result.geofence_summary).length?"See assessment below":"Unknown — no clearance inferred"}</p><EvidenceFacts value={result.geofence_summary}/>{result.warnings.map(item=><p className="result-warning" role="alert" key={item}>{item}</p>)}<details><summary>Evidence and limitations</summary><EvidenceFacts value={result.evidence}/>{result.limitations.map(item=><p key={item}>{item}</p>)}</details></div>}</section></div></div>;
}
