"use client";
import Link from "next/link";
import { AlertOctagon, BellRing, CalendarClock, CircleAlert, ExternalLink, Info, MapPin, Radio, ShieldAlert, TriangleAlert } from "lucide-react";
import type { AlertProviderStatus, AlertSeverity, AlertSourceType, AlertStatus, MarineAlert } from "@/features/alerts/types";

const labels=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase());
const severityIcon:Record<AlertSeverity,typeof Info>={INFO:Info,WATCH:CircleAlert,WARNING:TriangleAlert,SEVERE:ShieldAlert,CRITICAL:AlertOctagon};
export function AlertSeverityBadge({severity}:{severity:AlertSeverity}){const Icon=severityIcon[severity];return <span className={`alert-badge severity-${severity.toLowerCase()}`}><Icon size={12}/>{labels(severity)}</span>}
export function AlertStatusBadge({status}:{status:AlertStatus}){return <span className={`alert-badge status-${status.toLowerCase()}`}><Radio size={11}/>{labels(status)}</span>}
export function AlertSourceBadge({sourceType,provider}:{sourceType:AlertSourceType;provider:string}){return <span className={`alert-badge source-${sourceType.toLowerCase()}`}>{sourceType==="DEMO"?"DEMO DATA":sourceType==="OFFICIAL_ADVISORY"?"Official advisory":"Forecast risk"} · {provider}</span>}
export function ProviderStatusBadge({status}:{status:AlertProviderStatus}){return <span className={`provider-status provider-${status.toLowerCase()}`}>{labels(status)}</span>}
export function formatIst(value:string|null){if(!value)return "Not supplied";return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata",timeZoneName:"short"}).format(new Date(value));}
export function MarineAlertCard({alert,compact=false}:{alert:MarineAlert;compact?:boolean}){return <article className={`normalized-alert-card severity-border-${alert.severity.toLowerCase()} ${compact?"compact":""}`}><div className="normalized-alert-head"><div><div className="alert-badge-row"><AlertSeverityBadge severity={alert.severity}/><AlertStatusBadge status={alert.status}/></div><h3>{alert.title}</h3></div><AlertSourceBadge sourceType={alert.source_type} provider={alert.provider}/></div><p>{alert.summary??alert.description??"The provider supplied no narrative summary."}</p><div className="alert-facts"><span><MapPin size={13}/>{alert.affected_area??"Affected area supplied without a place label"}</span>{alert.distance_km!=null&&<span><MapPin size={13}/>{alert.is_inside?"Selected location is inside the advisory area":`${alert.distance_km.toFixed(1)} km from advisory geometry`}</span>}<span><CalendarClock size={13}/>Valid until {formatIst(alert.valid_until)}</span></div><div className="alert-card-actions"><Link href={`/alerts/${alert.id}`}>View details</Link>{(alert.geometry||alert.forecast_track)&&<Link href={`/map?alert=${alert.id}`}>View on map</Link>}{alert.source_url&&<a href={alert.source_url} target="_blank" rel="noreferrer">Provider source <ExternalLink size={12}/></a>}</div></article>}
export function AlertSafetyNote(){return <div className="alert-safety-note"><BellRing size={17}/><span>ORCA consolidates advisory information for decision support. Always follow official maritime, meteorological and local authority instructions.</span></div>}
