"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Anchor, Bell, Bot, ChartNoAxesCombined, ChevronDown, Clock3, History, LayoutDashboard, Map, Menu, Navigation, Route, Settings, ShieldAlert, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { selectedLocation } from "@/data/mock";
import { DataFreshnessBadge, DemoDataBadge } from "@/components/ui";
import { SystemStatusIndicator } from "@/components/system-status-indicator";
import { useAuth } from "@/components/auth-provider";

const navigation=[{href:"/dashboard",label:"Overview",icon:LayoutDashboard},{href:"/assistant",label:"AI Assistant",icon:Bot},{href:"/map",label:"Marine Map",icon:Map},{href:"/alerts",label:"Safety Alerts",icon:ShieldAlert},{href:"/routes",label:"Route Planner",icon:Route},{href:"/analytics",label:"Ocean Analytics",icon:ChartNoAxesCombined},{href:"/history",label:"History",icon:History},{href:"/settings",label:"Settings",icon:Settings}];
function UserProfile(){const {user,logout,isLoading}=useAuth();const initials=(user?.full_name||user?.email||"OR").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();return <div className="profile"><span>{initials}</span><div><strong>{user?.full_name||"ORCA User"}</strong><small>{user?.email||"Checking session…"}</small></div><button onClick={()=>void logout()} disabled={isLoading} aria-label="Log out" title="Log out"><ChevronDown size={15}/></button></div>}
function Sidebar({onClose}:{onClose?:()=>void}) { const path=usePathname();return <aside className="app-sidebar"><div className="side-top"><Link href="/dashboard" className="brand"><span className="brand-mark"><Anchor size={18}/></span>ORCA</Link><button className="mobile-only icon-button" onClick={onClose} aria-label="Close navigation"><X size={19}/></button></div><p className="sidebar-caption">MARINE INTELLIGENCE</p><nav>{navigation.map(item=>{const Icon=item.icon;const active=path===item.href;return <Link onClick={onClose} className={`side-link ${active?"active":""}`} href={item.href} key={item.href}><Icon size={18}/><span>{item.label}</span>{item.label==="Safety Alerts"&&<i className="alert-count">2</i>}</Link>})}</nav><div className="sidebar-bottom"><SystemStatusIndicator/><UserProfile/></div></aside> }
export function AppShell({children}:{children:ReactNode}) {const [open,setOpen]=useState(false);return <div className="app-shell"><div className={`drawer-overlay ${open?"visible":""}`} onClick={()=>setOpen(false)}/><div className={`drawer ${open?"open":""}`}><Sidebar onClose={()=>setOpen(false)}/></div><div className="desktop-sidebar"><Sidebar/></div><main className="app-main"><header className="app-header"><div className="header-location"><button className="mobile-only icon-button" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={20}/></button><span className="location-icon"><Navigation size={15}/></span><div><strong>{selectedLocation.name}</strong><small>{selectedLocation.coordinates}</small></div></div><div className="header-tools"><DataFreshnessBadge><Clock3 size={12}/>Updated 5 min ago</DataFreshnessBadge><DemoDataBadge/><button className="language">EN <ChevronDown size={13}/></button><button className="icon-button" aria-label="Notifications"><Bell size={18}/><i/></button><span className="avatar">LM</span></div></header>{children}</main></div> }
