import { Activity, Eye, Gauge, Wind, Waves } from "lucide-react";
import { degreesToCompass, formatMeasurement, updatedAgo } from "@/features/conditions/format";
import type { CombinedConditions, Measurement } from "@/features/conditions/types";

export function ConditionsPanel({conditions,loading,error,onRefresh,compact=false}:{conditions:CombinedConditions|null;loading:boolean;error:string|null;onRefresh:()=>void;compact?:boolean}){
  const weather=conditions?.weather?.current,marine=conditions?.marine?.current;
  return <section className={`conditions-panel ${compact?"compact":""}`}><div className="conditions-head"><div><p className="eyebrow">FORECAST CONDITIONS</p><h3>Weather & Marine</h3></div><button onClick={onRefresh} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>
    {error&&<p className="conditions-error">{error}</p>}
    {!conditions&&!loading&&!error&&<p className="conditions-empty">Select a map, saved, GPS, or profile-default location to load conditions.</p>}
    {conditions&&<><div className="conditions-grid"><Condition icon={<Waves/>} label="Wave height" value={marine?.wave_height} direction={marine?.wave_direction?.value} directionLabel="From"/><Condition icon={<Waves/>} label="Wave period" value={marine?.wave_period}/><Condition icon={<Wind/>} label="Wind" value={weather?.wind_speed} direction={weather?.wind_direction?.value} directionLabel="From"/><Condition icon={<Gauge/>} label="SST" value={marine?.sea_surface_temperature}/><Condition icon={<Activity/>} label="Current" value={marine?.ocean_current_speed} direction={marine?.ocean_current_direction?.value} directionLabel="Toward"/><Condition icon={<Waves/>} label="Swell" value={marine?.swell_height} direction={marine?.swell_direction?.value} directionLabel="From"/><Condition icon={<Eye/>} label="Visibility" value={weather?.visibility}/><Condition icon={<Gauge/>} label="Temperature" value={weather?.temperature}/><Condition icon={<Activity/>} label="Sea level" value={marine?.sea_level_height}/></div><p className="conditions-source">{conditions.sources.map(source=>source.dataset).join(" · ")||"Providers unavailable"} · {updatedAgo(conditions.retrieved_at)} · {conditions.status}</p>{conditions.marine?.limitations[0]&&<p className="conditions-limit">{conditions.marine.limitations[0]}</p>}{Object.values(conditions.errors).map(message=><p className="conditions-error" key={message}>{message}</p>)}<details className="conditions-evidence"><summary>Forecast evidence</summary>{[...(conditions.weather?.evidence??[]),...(conditions.marine?.evidence??[])].map(item=><div key={`${item.source}-${item.parameter}`}><span>{item.parameter.replaceAll("_"," ")}</span><b>{item.value} {item.unit}</b><small>{item.source} · forecast {new Date(item.observed_at??item.retrieved_at).toLocaleString()}</small></div>)}</details></>}
  </section>;
}
function Condition({icon,label,value,direction,directionLabel}:{icon:React.ReactNode;label:string;value:Measurement|null|undefined;direction?:number;directionLabel?:"From"|"Toward"}){return <div><span>{icon}{label}</span><b>{formatMeasurement(value)}</b>{direction!=null&&<small>{directionLabel} {Math.round(direction)}° {degreesToCompass(direction)}</small>}</div>}
