"use client";
import Link from "next/link";
import { ArrowRight, Bot, Send, ShieldCheck, Sparkles } from "lucide-react";
import type { ReactNode } from "react";
import type { MapLayer } from "@/types";
import type { PFZResponse } from "@/features/pfz/types";
import { DataFreshnessBadge, DemoDataBadge } from "@/components/ui";

export function MarineMetricCard({label,value,detail,icon,status="DEMO"}:{label:string;value:string;detail:string;icon:ReactNode;status?:"DEMO"|"CURRENT"|"UNAVAILABLE"}) {return <article className="metric-card"><div className="metric-top"><span>{icon}</span>{status==="DEMO"?<DemoDataBadge/>:<DataFreshnessBadge>{status==="CURRENT"?"Current forecast":"Unavailable"}</DataFreshnessBadge>}</div><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>}
export function PFZCard({data,loading,error}:{data:PFZResponse|null;loading?:boolean;error?:string|null}){const item=data?.pfzs[0];const demo=item?.status==="DEMO";return <article className="pfz-card"><div className="card-top"><div><p className="card-label">NEAREST POTENTIAL FISHING ZONE</p>{demo?<DemoDataBadge/>:<DataFreshnessBadge>{item?.status??"Not checked"}</DataFreshnessBadge>}</div><span className="pfz-compass">{item?.bearing_cardinal??"—"}</span></div>{loading?<p>Checking PFZ advisories…</p>:error?<p>PFZ service unavailable. This is not a no-PFZ result.</p>:item?<><div className="pfz-stats"><div><strong>{item.distance_km?.toFixed(1)??"—"} <small>km</small></strong><span>Distance</span></div><div><strong>{item.bearing_degrees?.toFixed(0)??"—"}°</strong><span>Bearing</span></div><div><strong>{item.status}</strong><span>Advisory state</span></div></div><p>{item.name} · {item.provider}{item.advisory_date?` · advisory ${item.advisory_date}`:""}</p></>:<p>{data?.result_state==="NO_PFZ_WITHIN_RADIUS"?"No current PFZ within the selected search radius.":"No PFZ advisory is available yet."}</p>}<Link className="inline-link" href="/map">View on Map <ArrowRight size={14}/></Link></article>}
export function QuickPrompt({children}:{children:ReactNode}){return <Link className="quick-prompt" href="/assistant"><Sparkles size={14}/>{children}<ArrowRight size={13}/></Link>}
export function ChatMessage({role,children}:{role:"user"|"orca";children:ReactNode}) {return <article className={`chat-message ${role}`}><span className="chat-avatar">{role==="orca"?<Bot size={17}/>:"LM"}</span><div><small>{role==="orca"?"ORCA":"YOU"}</small><div className="message-bubble">{children}</div></div></article>}
export function AgentActivity(){return <div className="agent-activity"><div><Bot size={17}/><strong>ORCA Analysis</strong><DemoDataBadge label="Demonstration"/></div><ol>{["Understanding query","Checking marine conditions","Checking weather","Evaluating hazards","Assessing risk","Preparing recommendation"].map((x,i)=><li key={x}><i className={i<5?"done":""}/>{x}</li>)}</ol></div>}
export function LayerToggle({layer,onChange}:{layer:MapLayer;onChange:(id:string)=>void}){return <label className="layer-toggle"><span><i style={{background:layer.color}}/>{layer.label}</span><input checked={layer.enabled} onChange={()=>onChange(layer.id)} type="checkbox"/><b/></label>}
export function ChartCard({title,children,status="DEMO"}:{title:string;children:ReactNode;status?:"DEMO"|"CURRENT"}){return <article className="chart-card"><div className="chart-head"><div><p className="card-label">OCEAN ANALYTICS</p><h3>{title}</h3></div>{status==="DEMO"?<DemoDataBadge/>:<DataFreshnessBadge>Forecast</DataFreshnessBadge>}</div>{children}</article>}
export function AssistantInput(){return <div className="assistant-input"><input aria-label="Ask ORCA" placeholder="Ask about weather, fishing zones, waves or marine safety…"/><button aria-label="Send message"><Send size={17}/></button></div>}
export function Notice(){return <div className="notice"><ShieldCheck size={16}/><span>Prototype decision-support only — not certified navigational guidance.</span></div>}
