"use client";
import Link from "next/link";
import { ArrowRight, Bot, Send, ShieldCheck, Sparkles } from "lucide-react";
import type { ReactNode } from "react";
import type { MapLayer, RiskAssessment } from "@/types";
import { DataFreshnessBadge, DemoDataBadge } from "@/components/ui";

export function MarineMetricCard({label,value,detail,icon,status="DEMO"}:{label:string;value:string;detail:string;icon:ReactNode;status?:"DEMO"|"CURRENT"|"UNAVAILABLE"}) {return <article className="metric-card"><div className="metric-top"><span>{icon}</span>{status==="DEMO"?<DemoDataBadge/>:<DataFreshnessBadge>{status==="CURRENT"?"Current forecast":"Unavailable"}</DataFreshnessBadge>}</div><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>}
export function RiskCard({risk}:{risk:RiskAssessment}) {return <section className="risk-card"><div><p className="card-label">RISK ASSESSMENT · DEMONSTRATION ONLY</p><h2>RISK ENGINE NOT CONNECTED</h2><p className="risk-copy">The score below remains a labeled interface fixture. ORCA does not infer safety from forecast metrics in Step 6.</p><div className="factor-row">{risk.factors.map(f=><span key={f}>{f} · demo</span>)}</div></div><div className="gauge"><div><strong>{risk.score}</strong><small>/ 100</small><span>Demo score</span></div></div></section>}
export function PFZCard(){return <article className="pfz-card"><div className="card-top"><div><p className="card-label">NEAREST POTENTIAL FISHING ZONE</p><DemoDataBadge/></div><span className="pfz-compass">SE</span></div><div className="pfz-stats"><div><strong>14.2 <small>km</small></strong><span>Distance</span></div><div><strong>48 <small>min</small></strong><span>Estimated travel</span></div><div><strong>High</strong><span>Confidence</span></div></div><p>South-East from selected location</p><Link className="inline-link" href="/map">View on Map <ArrowRight size={14}/></Link></article>}
export function QuickPrompt({children}:{children:ReactNode}){return <Link className="quick-prompt" href="/assistant"><Sparkles size={14}/>{children}<ArrowRight size={13}/></Link>}
export function ChatMessage({role,children}:{role:"user"|"orca";children:ReactNode}) {return <article className={`chat-message ${role}`}><span className="chat-avatar">{role==="orca"?<Bot size={17}/>:"LM"}</span><div><small>{role==="orca"?"ORCA":"YOU"}</small><div className="message-bubble">{children}</div></div></article>}
export function AgentActivity(){return <div className="agent-activity"><div><Bot size={17}/><strong>ORCA Analysis</strong><DemoDataBadge label="Demonstration"/></div><ol>{["Understanding query","Checking marine conditions","Checking weather","Evaluating hazards","Assessing risk","Preparing recommendation"].map((x,i)=><li key={x}><i className={i<5?"done":""}/>{x}</li>)}</ol></div>}
export function LayerToggle({layer,onChange}:{layer:MapLayer;onChange:(id:string)=>void}){return <label className="layer-toggle"><span><i style={{background:layer.color}}/>{layer.label}</span><input checked={layer.enabled} onChange={()=>onChange(layer.id)} type="checkbox"/><b/></label>}
export function ChartCard({title,children,status="DEMO"}:{title:string;children:ReactNode;status?:"DEMO"|"CURRENT"}){return <article className="chart-card"><div className="chart-head"><div><p className="card-label">OCEAN ANALYTICS</p><h3>{title}</h3></div>{status==="DEMO"?<DemoDataBadge/>:<DataFreshnessBadge>Forecast</DataFreshnessBadge>}</div>{children}</article>}
export function AssistantInput(){return <div className="assistant-input"><input aria-label="Ask ORCA" placeholder="Ask about weather, fishing zones, waves or marine safety…"/><button aria-label="Send message"><Send size={17}/></button></div>}
export function Notice(){return <div className="notice"><ShieldCheck size={16}/><span>Prototype decision-support only — not certified navigational guidance.</span></div>}
