import type { FeatureCollection, GeoJsonProperties, Geometry } from "geojson";
import type { MarineMapLayer } from "@/features/map/types";

export const marineLayers: MarineMapLayer[] = [
  {
    id: "pfz",
    name: "Potential Fishing Zones (PFZ)",
    description: "Real-time INCOIS oceanic thermal and chlorophyll front advisories.",
    category: "Fishing",
    enabled: true,
    available: true,
    dataStatus: "LIVE",
    legend: "Active Fishing Zones",
    source: "INCOIS Marine Fisheries Network",
    color: "#16a085",
  },
  {
    id: "sst",
    name: "Sea Surface Temperature (SST)",
    description: "Sentinel-3 SLSTR & Copernicus satellite observations (DEMO SST grid compatible).",
    category: "Ocean",
    enabled: true,
    available: true,
    dataStatus: "LIVE",
    legend: "°C · Real-time Sea Surface Temperature",
    source: "Copernicus Marine / Sentinel-3",
    color: "#e27841",
  },
  {
    id: "chlorophyll",
    name: "Chlorophyll-a Concentration",
    description: "NASA Aqua-MODIS & Sentinel-3 OLCI ocean color data.",
    category: "Ocean",
    enabled: true,
    available: true,
    dataStatus: "LIVE",
    legend: "mg/m³ · Biological Productivity",
    source: "Copernicus Marine / NASA OceanColor",
    color: "#79a951",
  },
  {
    id: "ais",
    name: "Live AIS Vessel Traffic",
    description: "Real-time tracking of commercial, tanker, cargo & fishing vessels.",
    category: "Maritime Traffic",
    enabled: true,
    available: true,
    dataStatus: "LIVE",
    legend: "Commercial & Fishing Vessels",
    source: "AISStream / Coastal Receiver Network",
    color: "#3b82f6",
  },
  {
    id: "alerts",
    name: "Marine Multi-Hazard Alerts",
    description: "Official IMD Common Alerting Protocol (CAP) and cyclone advisories.",
    category: "Weather & Safety",
    enabled: true,
    available: true,
    dataStatus: "LIVE",
    legend: "Severity-labelled advisory geometry",
    source: "India Meteorological Department (IMD)",
    color: "#d95d16",
  },
  {
    id: "waves",
    name: "Wave & Swell Conditions",
    description: "Real-time significant wave height & swell spectra.",
    category: "Ocean",
    enabled: false,
    available: true,
    dataStatus: "LIVE",
    legend: "Wave Height (m)",
    source: "Open-Meteo Marine Weather API",
    color: "#22b8cf",
  },
  {
    id: "currents",
    name: "Ocean Currents",
    description: "Surface velocity & ocean current vectors.",
    category: "Ocean",
    enabled: false,
    available: true,
    dataStatus: "LIVE",
    legend: "m/s Current Velocity",
    source: "Copernicus Marine / Open-Meteo",
    color: "#6b7dc4",
  },
  {
    id: "weather",
    name: "Coastal Weather & Wind",
    description: "Hourly coastal wind speed, gusts & weather forecasts.",
    category: "Weather & Safety",
    enabled: false,
    available: true,
    dataStatus: "LIVE",
    legend: "Wind & Visibility",
    source: "Open-Meteo Weather Forecast API",
    color: "#6495bd",
  },
  {
    id: "restricted",
    name: "Restricted Maritime Zones",
    description: "Active naval exercises, coastal security & anchorage boundaries.",
    category: "Boundaries",
    enabled: false,
    available: true,
    dataStatus: "LIVE",
    legend: "Restricted Maritime Zones",
    source: "Indian Coast Guard / DG Shipping",
    color: "#c53030",
  },
  {
    id: "route",
    name: "Optimized Safe Marine Route",
    description: "A* bathymetry and hazard-avoidance navigation channel.",
    category: "Navigation",
    enabled: true,
    available: true,
    dataStatus: "LIVE",
    legend: "Safe Navigation Channel",
    source: "ORCA Marine Routing Engine",
    color: "#f6c452",
  },
  {
    id: "saved",
    name: "Saved Waypoints",
    description: "Your explicitly saved locations.",
    category: "Navigation",
    enabled: true,
    available: true,
    dataStatus: "LIVE",
    legend: "Saved location",
    source: "Your ORCA account",
    color: "#117ea6",
  },
];

export const demoFeatures: FeatureCollection<Geometry, GeoJsonProperties> = {
  type: "FeatureCollection",
  features: [],
};

