"""Frozen initial schema; independent of future ORM model imports.

Snapshot of the original 7361284 baseline. Later revisions own later fields.
Revision ID: 20260907_01
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql
revision = "20260907_01"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_logs',
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source_logs'))
    )
    op.create_index(op.f('ix_data_source_logs_provider'), 'data_source_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_data_source_logs_status'), 'data_source_logs', ['status'], unique=False)
    op.create_table('marine_alerts',
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('alert_type', sa.Enum('CYCLONE', 'HIGH_WAVES', 'STRONG_WIND', 'LIGHTNING', 'HEAVY_RAIN', 'LOW_VISIBILITY', 'GEOFENCE', 'OTHER', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marine_alerts'))
    )
    op.create_index('ix_alert_validity', 'marine_alerts', ['valid_from', 'valid_until'], unique=False)
    op.create_index(op.f('ix_marine_alerts_alert_type'), 'marine_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_marine_alerts_external_id'), 'marine_alerts', ['external_id'], unique=False)
    op.create_index(op.f('ix_marine_alerts_source'), 'marine_alerts', ['source'], unique=False)
    op.create_index(op.f('ix_marine_alerts_valid_from'), 'marine_alerts', ['valid_from'], unique=False)
    op.create_index(op.f('ix_marine_alerts_valid_until'), 'marine_alerts', ['valid_until'], unique=False)
    op.create_table('marine_zones',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_type', sa.Enum('EEZ', 'INTERNATIONAL_BOUNDARY', 'RESTRICTED_WATER', 'MARINE_PROTECTED_AREA', 'ECOLOGICALLY_SENSITIVE_ZONE', 'CUSTOM', name='zone_type'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marine_zones'))
    )
    op.create_index(op.f('ix_marine_zones_source'), 'marine_zones', ['source'], unique=False)
    op.create_index(op.f('ix_marine_zones_zone_type'), 'marine_zones', ['zone_type'], unique=False)
    op.create_table('potential_fishing_zones',
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('advisory_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_potential_fishing_zones'))
    )
    op.create_index('ix_pfz_validity', 'potential_fishing_zones', ['valid_from', 'valid_until'], unique=False)
    op.create_index(op.f('ix_potential_fishing_zones_external_id'), 'potential_fishing_zones', ['external_id'], unique=False)
    op.create_index(op.f('ix_potential_fishing_zones_source'), 'potential_fishing_zones', ['source'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), nullable=False),
    sa.Column('preferred_units', sa.String(length=16), nullable=False),
    sa.Column('default_latitude', sa.Float(), nullable=True),
    sa.Column('default_longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_latitude BETWEEN -90 AND 90', name=op.f('ck_users_user_default_latitude_range')),
    sa.CheckConstraint('default_longitude BETWEEN -180 AND 180', name=op.f('ck_users_user_default_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('marine_routes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='route_risk_level'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_marine_routes_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marine_routes'))
    )
    op.create_index(op.f('ix_marine_routes_user_id'), 'marine_routes', ['user_id'], unique=False)
    op.create_table('refresh_token_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_token_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token_sessions'))
    )
    op.create_index(op.f('ix_refresh_token_sessions_expires_at'), 'refresh_token_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_sessions_jti'), 'refresh_token_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_token_sessions_revoked_at'), 'refresh_token_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_sessions_user_id'), 'refresh_token_sessions', ['user_id'], unique=False)
    op.create_table('saved_locations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.Enum('HOME_HARBOUR', 'FISHING_HARBOUR', 'FISHING_SPOT', 'CUSTOM', name='location_type'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_locations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_locations'))
    )
    op.create_index(op.f('ix_saved_locations_user_id'), 'saved_locations', ['user_id'], unique=False)
    op.create_table('alert_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('saved_location_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('CYCLONE', 'HIGH_WAVES', 'STRONG_WIND', 'LIGHTNING', 'HEAVY_RAIN', 'LOW_VISIBILITY', 'GEOFENCE', 'OTHER', name='subscription_alert_type'), nullable=False),
    sa.Column('minimum_severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='minimum_severity'), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['saved_location_id'], ['saved_locations.id'], name=op.f('fk_alert_subscriptions_saved_location_id_saved_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alert_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_subscriptions'))
    )
    op.create_index(op.f('ix_alert_subscriptions_saved_location_id'), 'alert_subscriptions', ['saved_location_id'], unique=False)
    op.create_index(op.f('ix_alert_subscriptions_user_id'), 'alert_subscriptions', ['user_id'], unique=False)
    op.create_table('marine_query_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_marine_query_logs_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_marine_query_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marine_query_logs'))
    )
    op.create_index(op.f('ix_marine_query_logs_conversation_id'), 'marine_query_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_marine_query_logs_status'), 'marine_query_logs', ['status'], unique=False)
    op.create_index(op.f('ix_marine_query_logs_user_id'), 'marine_query_logs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Initial schema downgrade is destructive; restore a reviewed backup instead")
